FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

EXPOSE 5173

# --host 0.0.0.0 ist notwendig, damit der Port aus dem Container erreichbar ist
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
